name: Compile Stage

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  login:
      runs-on: ubuntu-latest
      steps:
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  compile_and_test:
    runs-on: ubuntu-latest
    container: i2a2/iriocore-docker:latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile Code
      run: make compile -j

    - name: Run UnitTests
      run: make test
