name: C/C++ CI - Compilation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt install -y unzip
        sudo apt install -y wget
        sudo apt install -y rsync
        wget https://download.ni.com/support/softlib/MasterRepository/LinuxDrivers2023Q4/NILinux2023Q4DeviceDrivers.zip
        unzip NILinux2023Q4DeviceDrivers.zip
        cd NILinux2023Q4DeviceDrivers
        sudo dpkg -i ni-ubuntu*
        sudo apt update
        sudo apt install -y ni-syscfg-devel
        sudo apt install -y ni-flexrio-modulario-libs-devel
        sudo apt install -y libpugixml-dev
        sudo apt install -y libgtest-dev

  compile:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:   
    - name: Compile Code
      run: make

  run_unittests:
    runs-on:  ubuntu-lastest
    needs:  compile
    steps:
    - name: Run Unit Tests
      run: |
        cd target/test/c++/unittest
        ./test_ut_iriov2cpp
