name: Compile Stage

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.h'
jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get install -y unzip
        sudo apt-get install -y wget
        sudo apt-get install -y rsync
        wget https://download.ni.com/support/softlib/MasterRepository/LinuxDrivers2023Q4/NILinux2023Q4DeviceDrivers.zip
        unzip NILinux2023Q4DeviceDrivers.zip
        cd NILinux2023Q4DeviceDrivers
        sudo dpkg -i ni-ubuntu*
        sudo apt-get update
        sudo apt-get install -y ni-syscfg-devel
        sudo apt-get install -y ni-flexrio-modulario-libs-devel
        sudo apt-get install -y libpugixml-dev
        sudo apt-get install -y libgtest-dev
        
    - name: Compile Code
      run: make compile -j

    - name: Run UnitTests
      run: make test
