name: Generate Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  PACKAGE_DIR: "target/packages/x86_64"

jobs:
  package:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/i2a2/iriocore-docker:v1.0
    steps:
    - name: Install alien
      run: |
        dnf config-manager --set-enabled crb
        dnf install -y alien

    - uses: actions/checkout@v3  
    - name: Generate RPM packages
      run: | 
        make package -j
        ls $PACKAGE_DIR

    - name: Generate DEB packages
      run: |
        cd $PACKAGE_DIR
        alien *.rpm
        ls .
        cd -
    
    - name: Generate release
      uses: softprops/action-gh-release@v2
      with:
        files: ${PACKAGE_DIR}/*
